name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      deploy_token:
        description: 'Deployment token'
        required: true
      deploy_env:
        description: 'Environment to deploy (dev/staging/prod)'
        required: true
      api_key:
        description: 'API Key for integration'
        required: true
      db_password:
        description: 'Database password'
        required: true
      encryption_key:
        description: 'Encryption key'
        required: true

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          DEPLOY_ENV="${{ github.event.inputs.deploy_env }}"
          DEPLOY_TOKEN="${{ github.event.inputs.deploy_token }}"
          API_KEY="${{ github.event.inputs.api_key }}"
          DB_PASSWORD="${{ github.event.inputs.db_password }}"
          ENCRYPTION_KEY="${{ github.event.inputs.encryption_key }}"

          echo "Deployment Environment: $DEPLOY_ENV"
          echo "Deployment Token: $DEPLOY_TOKEN"
          echo "API Key: $API_KEY"
          echo "Database Password: $DB_PASSWORD"
          echo "Encryption Key: $ENCRYPTION_KEY"
